#+Title: CPDOC

Project CPDOC.

System Requirements:

- Elastic Search 
- Allegro Common Lisp

* Import Elastic Search

#+BEGIN_SRC lisp
(mapc (lambda (file) (clesc:es/add "dhbb" "doc" (extract-meta file)))
	     (directory "*.text"))
#+END_SRC
=======

* Roadmap

Os dados estão no github. O JSA é sobre explorar o DHBB do CPDOC
usando NLP para extração de informações.

* Analise FreeLing nos dicionários

- explicar porque “movimentação_financeira” e
  “imposto_provisório_sobre_movimentação_financeira” estão sendo
  identificados como pessoas. (Valeria em Jul 7)

- explicar ch com 292 ocorrências no DHBB.

- verificar ocorrências do verbo "pelar". Como evitar erro no
  tratamento das preposições pelo/pela.

- listas para serem preparadas:

 1- lugares
 2- nomes de pessoas
 3- nomes de organizacoes (incluindo partidos políticos)
  http://pt.wikipedia.org/wiki/Categoria:Pol%C3%ADticos_do_Brasil
  http://www.tse.jus.br/partidos/partidos-politicos
 4- acronimos/abreviacoes
 5- entidades-outras (AI-5 e Revolucao de 30).
 6- lista de cargos (não estaria junto com acrônimos?)
 7- mwes, http://en.wikipedia.org/wiki/Multiword_expression. 

- adicionar os lugares do GeoWordNet aos "locations" do Freeling?

- re-run freeling com listas

- n-grams for MWE extraction.

* Links

- http://git2prov.org
- http://github.com/cpdoc/

