
Nesta pasta, contém os arquivos .sent onde tanto Freeling quanto
OpenNLP convergiram em sua segmentação, ou seja, onde temos uma alta
probabilidade de serem segmentações corretas.

Para gerar os arquivos, rode nesta pasta o comando abaixo após 
iniciar o servidor freeling (vide abaixo).

$ ./make.sh

* Freeling 

deprecated code:

#+BEGIN_SRC batch
$ sbcl
(load "splitter.lisp")
(sb-ext:save-lisp-and-die "splitter" :toplevel #'main :executable t)
#+END_SRC

Configure Freling

- the file splitter.dat must add the markers « »
- the file tokenizer.dat must remove the abbreviation "pt."

Open Freeling server on another terminal:

  analyze -f pt.cfg --output json --noflush --server --port 8000

* OpenNLP
  
Until commit 59cf669 we have Detector.java

compile:
#+BEGIN_SRC bash
javac -cp "/Users/ar/work/apache-opennlp-1.9.2/lib/*" Detector.java
#+END_SRC

run:
#+BEGIN_SRC bash
java -cp "/Users/ar/work/apache-opennlp-1.9.2/lib/*:." Detector
#+END_SRC

Now we just use `make.sh`

** training the model

Os arquivos pertinentes ao treino do modelo são:

sentences_gold.sent
param.txt

O arquivo amostras_DHBB.sent contém uma amostra de aproximadamente 200
frases do DHBB onde o modelo pré treinado do Bosque errou a
segmentação O arquivo param.txt possui os parâmetros do treino. A
ideia é unir essas frases ao Bosque e retreinar o modelo.

Para tal, proceda da seguinte maneira, faça o download do arquivo de
treino do Bosque:

: wget https://github.com/UniversalDependencies/UD_Portuguese-Bosque/raw/master/pt_bosque-ud-train.conllu

Utilize o conversor do OpenNLP para extrair as sentenças do arquivo
.conllu de treino do Bosque.

: opennlp SentenceDetectorConverter conllu -sentencesPerSample 10 -data pt_bosque-ud-train.conllu > bosque_train.sent

Agora una os dois arquivos 

: cat bosque_train.sent amostras_dhbb.sent > arquivo_treino.sent

Use o arquivo arquivo_treino.sent para treinar o modelo

: opennlp SentenceDetectorTrainer -lang portuguese -model bosque_model.opennlp -data arquivo_treino.sent -encoding utf-8 -params param.txt

Remova os arquivos não mais necessários

: rm amostras_dhbb.sent arquivo_treino.sent bosque_train.sent pt_bosque-ud-train.conllu 

Ou rode

: make_model.sh path/to/opennlp

* Next Stesp

 - Issue 
 - https://stackoverflow.com/questions/47274540/how-to-improve-sentence-segmentation-of-nltk

